Add egress sg rule var
schubergphilis/terraform-aws-mcaf-lambda pull request #41
Opened 2022-05-29 22:52 UTC by rogiermccv

Currently the lambda function gets a default egress rule that allows all traffic. This causes findings in security hub and is difficult to explain in PCIDSS firewall reviews. This PR adds a variable to control the creation of the egress rule. By default this is off to set a secure default, but when this is enabled, the original behaviour is replicated.

2022-05-30 12:47 UTC, marwinbaumannsbp commented on main.tf
> +  count             = var.enable_all_egress_rule ? 1 : 0
can you change the count to also depend on var.subnet_ids. both var.subnet_ids and var.enable_all_egress_rule need to be set before this resource is created.

2022-05-30 12:47 UTC, marwinbaumannsbp commented on variables.tf
> +  description = "A flag to enable/disable adding the all ports egress rule to the service security group"
Maybe change the description to something like this? I'm looking for a sentence that links this to the vpc creation. You need to run the lambda in a vpc in order for the variable to make sense. 

`If the lamba is deployed in a VPC by adding `subnet_ids`, this flag controls the creation of an all ports egress rule to the security group attached to the lambda.`

2022-05-30 22:50 UTC, shoekstra requested changes

2022-05-30 22:50 UTC, shoekstra commented on variables.tf
> +  default     = false
```suggestion
  default     = true
```

This should be set to `true` to maintain compatibility, otherwise we're introducing a breaking change for others. Those that don't want to enable it can then opt out.

2022-05-30 22:50 UTC, shoekstra commented on variables.tf
> +variable "enable_all_egress_rule" {
```suggestion
variable "create_ allow_all_egress_rule" {
```

I think `create` is more descriptive than `enable` 🙂

2022-05-30 22:50 UTC, shoekstra commented on variables.tf
> +  description = "A flag to enable/disable adding the all ports egress rule to the service security group"
We could make this more terse, e.g.

`Controls whether an egress rule to any ipv4 address will be created`

Or:

`Controls whether an egress rule to any ipv4 address will be created when the lambda is configured to run in a VPC`

This feels wordy but mentions the relation to the VPC config.

2022-05-30 22:54 UTC, rogiermccv commented on variables.tf
> +  description = "A flag to enable/disable adding the all ports egress rule to the service security group"
updated description

2022-05-30 22:55 UTC, rogiermccv commented on main.tf
> +  count             = var.enable_all_egress_rule ? 1 : 0
added extra dependency,

2022-05-30 22:58 UTC, rogiermccv commented on variables.tf
> +  default     = false
@shoekstra this default setting was specifically requested by @marwinbaumannsbp to set a secure default, as that is what mcaf is supposed to be. he suggested raising the version to 0.3.0 to indicate a major change. I understand your suggestion, but I think setting a secure default makes more sense in this case. Can you discuss with @marwinbaumannsbp how to proceed?

2022-05-30 23:02 UTC, rogiermccv commented on variables.tf
> +variable "enable_all_egress_rule" {
updated the var name 👍

2022-05-30 23:03 UTC, rogiermccv commented on variables.tf
> +  description = "A flag to enable/disable adding the all ports egress rule to the service security group"
updated to new suggestion.

2022-05-31 07:46 UTC, shoekstra approved these changes

2022-05-31 07:47 UTC, merged