add empty egress and ingress inline definition
schubergphilis/terraform-aws-mcaf-lambda pull request #43
Opened 2022-06-20 07:52 UTC by rogiermccv

Add an empty ingress and egress definition to remove existing security group rules that were previously created by inline rules. Now these are moved to external security group rule definitions to allow the egress to be enabled and disabled via a count.

2022-06-20 09:42 UTC, svanharmelen requested changes

2022-06-20 09:42 UTC, svanharmelen commented on main.tf
> +  egress  = []
If they are single line fields, please do not put them in a separated block but order them alphabetically with the other fields.

2022-06-20 09:43 UTC, svanharmelen commented on main.tf
> +  egress  = []
And did you check and confirm if this actually solves your issue? As I would expect the old rules to be deleted when removing these blocks...

2022-06-20 16:39 UTC, rogiermccv commented on main.tf
> +  egress  = []
I've updated the order of the variables. The reason I've started this PR is that I updated the module version to 0.3.0 in one of our projects and disabled creation of egress security group rules via `create_allow_all_egress_rule = false`. I expected this to remove the existing egress rule but this was not the case as it was created as an inline sgrule. That inline sgrule was not defined anymore, and terraform does not remove it in that case (see for example: https://github.com/hashicorp/terraform-provider-aws/issues/1555). To force the removal of the old egress inline rule, I've set these empty sets.

2022-06-21 06:57 UTC, svanharmelen commented on main.tf
> +  egress  = []
Thanks for fixing the PR and leaving the additional info!

2022-06-21 06:57 UTC, svanharmelen approved these changes

2022-06-21 06:57 UTC, merged