feature: Add role name to output of Lambda when this is available
schubergphilis/terraform-aws-mcaf-lambda pull request #73
Opened 2024-04-15 11:42 UTC by stefanwb

Signed-off-by: Stefan Wessels Beljaars <swesselsbeljaars@schubergphilis.com>

2024-04-15 12:13 UTC, marwinbaumannsbp submitted a review, later dismissed

2024-04-15 12:16 UTC, shoekstra requested changes

2024-04-15 12:16 UTC, shoekstra commented on outputs.tf
> +  value       = var.role_arn != null ? var.role_arn : aws_iam_role.default[0].name
These are 2 different values though? One is an ARN and one is a name... Can you clarify pls?

2024-04-16 13:35 UTC, shoekstra approved these changes

2024-04-16 13:38 UTC, merged